namespace SingBoxLib.Configuration.Serialization;

/// <summary>
/// Pre-compiled source-generated JSON serialization context for SingBoxLib models.
/// </summary>
[JsonSourceGenerationOptions(WriteIndented = false, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]
[JsonSerializable(typeof(SingBoxConfig))]
[JsonSerializable(typeof(InboundConfig))]
[JsonSerializable(typeof(OutboundConfig))]
[JsonSerializable(typeof(EndpointConfig))]
[JsonSerializable(typeof(RouteRuleBase))]
[JsonSerializable(typeof(RouteRuleSetBase))]
[JsonSerializable(typeof(RouteRuleHeadlessBase))]
[JsonSerializable(typeof(DnsRuleBase))]
[JsonSerializable(typeof(TransportConfig))]
[JsonSerializable(typeof(DnsRule))]
[JsonSerializable(typeof(DnsLogicalRule))]
[JsonSerializable(typeof(RouteRule))]
[JsonSerializable(typeof(RouteLogicalRule))]
[JsonSerializable(typeof(RouteRuleHeadless))]
[JsonSerializable(typeof(RouteRuleHeadlessLogical))]
[JsonSerializable(typeof(WireGuardEndpoint))]
[JsonSerializable(typeof(LogInfo))]
[JsonSerializable(typeof(TrafficInfo))]
[JsonSerializable(typeof(VersionInfo))]
[JsonSerializable(typeof(ConfigInfo))]
[JsonSerializable(typeof(RuleInfo))]
[JsonSerializable(typeof(ProxyInfo))]
[JsonSerializable(typeof(ProxyDelayInfo))]
[JsonSerializable(typeof(VMessProfileModel))]
[JsonSerializable(typeof(ClashApiWrapper.ReloadConfigRequest))]
[JsonSerializable(typeof(ClashApiWrapper.RulesResponse))]
[JsonSerializable(typeof(ClashApiWrapper.ProxiesResponse))]
[JsonSerializable(typeof(List<InboundConfig>))]
[JsonSerializable(typeof(InboundConfig[]))]
[JsonSerializable(typeof(List<OutboundConfig>))]
[JsonSerializable(typeof(OutboundConfig[]))]
[JsonSerializable(typeof(List<SingBoxConfig>))]
[JsonSerializable(typeof(SingBoxConfig[]))]
[JsonSerializable(typeof(List<EndpointConfig>))]
[JsonSerializable(typeof(EndpointConfig[]))]
[JsonSerializable(typeof(List<RouteRuleBase>))]
[JsonSerializable(typeof(RouteRuleBase[]))]
[JsonSerializable(typeof(List<RouteRuleSetBase>))]
[JsonSerializable(typeof(RouteRuleSetBase[]))]
[JsonSerializable(typeof(List<RouteRuleHeadlessBase>))]
[JsonSerializable(typeof(RouteRuleHeadlessBase[]))]
[JsonSerializable(typeof(List<DnsRuleBase>))]
[JsonSerializable(typeof(DnsRuleBase[]))]
[JsonSerializable(typeof(List<TransportConfig>))]
[JsonSerializable(typeof(TransportConfig[]))]
[JsonSerializable(typeof(List<DnsRule>))]
[JsonSerializable(typeof(DnsRule[]))]
[JsonSerializable(typeof(List<DnsLogicalRule>))]
[JsonSerializable(typeof(DnsLogicalRule[]))]
[JsonSerializable(typeof(List<RouteRule>))]
[JsonSerializable(typeof(RouteRule[]))]
[JsonSerializable(typeof(List<RouteLogicalRule>))]
[JsonSerializable(typeof(RouteLogicalRule[]))]
[JsonSerializable(typeof(List<RouteRuleHeadless>))]
[JsonSerializable(typeof(RouteRuleHeadless[]))]
[JsonSerializable(typeof(List<RouteRuleHeadlessLogical>))]
[JsonSerializable(typeof(RouteRuleHeadlessLogical[]))]
[JsonSerializable(typeof(List<WireGuardEndpoint>))]
[JsonSerializable(typeof(WireGuardEndpoint[]))]
public partial class SingBoxJsonContext : JsonSerializerContext
{
}
